### ISSUE TITLE
Proposal: Have different logging levels in `InfoLog`

### ISSUE THREAD

**Issue by abaire** [dracc/NevolutionX#108]
Right now all `outputLine`s are equal and are all displayed in the overlay if the overlay is enabled.
In practice there may be a subset of messages that are interesting to users, where the majority are only interesting to developers. 

We could extend `InfoLog` to have a `debugLine` (or add a log level to `outputLine`) and modify the config to allow users to set the verbosity of log output for the overlay and log viewer.

**Comment by dracc** [comment]
I think adding an extra argument to `InfoLog` would be the preferable solution. :)
