### ISSUE TITLE
Applications not showing in menu

### ISSUE THREAD

**Issue by Kystre** [dracc/NevolutionX#139]
Hello, i have attempted to load Xored Trainer Launcher by placing it in the 'E' partition under "Apps" subfolder and editing the json file to look for apps in that location "E:\\Apps\\Xored" however while the log shows that it has queried that folder, it says that it failed.

i should advise that i am doing this on the xemu xbox emulator using the precompiled qcow2 hdd image.

this is my first time opening an issue, please let me know if i should add or remove things in future.

![ftp xored dir listing](https://user-images.githubusercontent.com/11651205/137636362-d6de1b6b-91dc-4aa6-9c5f-94ebb7428cb3.PNG)

![dir scan failed](https://user-images.githubusercontent.com/11651205/137636049-92040f74-7b97-472a-8eeb-87abf9306909.png)

please see config.json file contents below:

> {
    "settings":
    {
        "network":
        {
            "enable": true,
            "use_dhcp": true,
            "static_ip": "10.0.1.7",
            "static_gateway": "10.0.1.1",
            "static_netmask": "255.255.255.0"
        },
        "ftp":
        {
            "enable": true,
            "username": "xbox",
            "password": "xbox",
            "port": 21
        },
        "sntp":
        {
            "enable": true,
            "port": 123,
            "server": "129.6.15.28"
        },
        "mount":
        {
            "enable_f": false,
            "enable_g": false
        },
        "logging":
        {
            "enable_overlay": true,
            "overlay_duration_frames": 30,
            "overlay_bg_alpha_int": 100
        },
        "homescreen":
        {
            "show_fps": false,
            "show_ip": true
        }
    },
    "menu":
    [
        {
            "label": "Games",
            "type": "scan",
            "path": "F:\\Games\\,G:\\Games"
        },
        {
            "label": "Applications",
            "type": "scan",
            "path": "E:\\Apps\\Xored"
        },
        {
            "label": "Launch DVD",
            "type": "launch",
            "path": "D:\\default.xbe"
        },
        {
            "label": "Settings",
            "type": "settings"
        },
        {
            "label": "Reboot",
            "type": "reboot"
        },
        {
            "label": "Power off",
            "type": "shutdown"
        },
        {
            "label": "Some stupid submenu",
            "type": "submenu"
        }
    ]
}

please see below for zip file with json file for testing as needed:
[config.json.zip](https://github.com/dracc/NevolutionX/files/7360397/config.json.zip)

**Comment by dracc** [comment]
You want the Path to point to `E:\\Apps` still, as it checks one level of subdirectories for files named `default.xbe`.

**Comment by Kystre** [comment]
i have done that and tried again; no change:

![apps empty](https://user-images.githubusercontent.com/11651205/137643274-498e180e-6c0f-4569-89be-f5d15efd84bd.PNG)


![dir scan e](https://user-images.githubusercontent.com/11651205/137643287-40644df6-af11-4a02-ba5c-43705aa48fd9.PNG)


> {
    "settings":
    {
        "network":
        {
            "enable": true,
            "use_dhcp": true,
            "static_ip": "10.0.1.7",
            "static_gateway": "10.0.1.1",
            "static_netmask": "255.255.255.0"
        },
        "ftp":
        {
            "enable": true,
            "username": "xbox",
            "password": "xbox",
            "port": 21
        },
        "sntp":
        {
            "enable": true,
            "port": 123,
            "server": "129.6.15.28"
        },
        "mount":
        {
            "enable_f": false,
            "enable_g": false
        },
        "logging":
        {
            "enable_overlay": true,
            "overlay_duration_frames": 30,
            "overlay_bg_alpha_int": 100
        },
        "homescreen":
        {
            "show_fps": false,
            "show_ip": true
        }
    },
    "menu":
    [
        {
            "label": "Games",
            "type": "scan",
            "path": "F:\\Games\\,G:\\Games"
        },
        {
            "label": "Applications",
            "type": "scan",
            "path": "E:\\Apps"
        },
        {
            "label": "Launch DVD",
            "type": "launch",
            "path": "D:\\default.xbe"
        },
        {
            "label": "Settings",
            "type": "settings"
        },
        {
            "label": "Reboot",
            "type": "reboot"
        },
        {
            "label": "Power off",
            "type": "shutdown"
        },
        {
            "label": "Some stupid submenu",
            "type": "submenu"
        }
    ]
}
