### ISSUE TITLE
Games path is hardcoded

### ISSUE THREAD

**Issue by dracc** [dracc/NevolutionX#20]
This is one of the first features that should be implemented in the settings screen.

**Comment by Teufelchen1** [comment]
Similar to #35 
I believe NevoX needs a general configuration file? 
If so, shall we open another issue for that?
Thinking of having no configuration will potentially lead to more 'issues', such as:
- No static IP support
- Recompilation/renaming/replacing for using a different background image
- No customisations at all except in code prior compilation 
- NevoX being hard to integrate into existing dashboards(i.e. launching it from xbmc)

**Comment by dracc** [comment]
Fixed in #47
