### ISSUE TITLE
Cannot build under macOS

### ISSUE THREAD

**Issue by Teufelchen1** [dracc/NevolutionX#33]
Hi 👋 

[Its possible this is a macOS problem and not one with Nevolution, how ever, I'm inexperienced with cpp & huge makefiles, so I can not be sure]

I'm using:
- `uname -a` : `Darwin hostname 18.7.0 Darwin Kernel Version 18.7.0`
- `clang --version` : `Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0`
- `make --verison` : `GNU Make 3.81`

I did:
1. (installing nxdk)
2. `git clone nevolution...`
3. `cmake .` (I'm not experienced with cmake!)
4. `make`

I expected:
- nice and calm compiling
- a binary file of some kind as a result

I got one error in step 4:
```sh
[ CXX      ] /Users/<user>/NevolutionX/main.obj
/Users/<user>/NevolutionX/main.cpp:1:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
make: *** [/Users/<user>/NevolutionX/main.obj] Error 1
```

Notes:
- most likely only affects modern macOS
- there is brew [documentation](https://docs.brew.sh/C++-Standard-Libraries) about libraries switching in macOS that could result in such an error 
- I created this example program:
```c++
#include <vector>

int main(void) {
    return 0;
}
```
and compiled it with `clang test.cpp`. It builds and runs just fine. 

There is [this](https://stackoverflow.com/questions/52679906/fatal-error-vector-file-not-found-with-xcode-10) stackoverflow entry that is likely related. Will try the suggested solution from it if there is no other option I could try.

**Comment by dracc** [comment]
You're on the right path. Building for Xbox should be easy as `make` if nxdk is cloned into the same parent directory as NevolutionX.
I don't have the equipment to test compiling for macOS myself but not finding `<vector>` sounds weird to me as it's part of STL. Since there already exists a makefile, it's not impossible that cmake collides with existing files - try running
```mkdir build
cd build
cmake ..
make``` from within the NevolutionX directory.

**Comment by Teufelchen1** [comment]
Following the suggested step resulted in `cmake` complaining about a missing `SDL2_ttf` module. I installed it via `brew install SDL2_ttf`. After that, I re-run the suggested steps, resulting in a new error 🤔 
```sh
~/NevolutionX (git)-[master] % git reset --hard
HEAD is now at 52d63e9 main: Use the new renderer functions
~/NevolutionX (git)-[master] % cd build
~/NevolutionX/build (git)-[master] %
~/NevolutionX/build (git)-[master] % cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/<user>/NevolutionX
~/NevolutionX/build (git)-[master] % make
make: *** No targets specified and no makefile found.  Stop.
~/NevolutionX/build (git)-[master] % cd ..                                                                                                                                                
~/NevolutionX (git)-[master] % make
Scanning dependencies of target NevolutionX
[ 11%] Building CXX object CMakeFiles/NevolutionX.dir/main.cpp.o
/Users/<user>/NevolutionX/main.cpp:11:10: fatal error: 'threads.h' file not found
#include <threads.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/NevolutionX.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/NevolutionX.dir/all] Error 2
make: *** [all] Error 2
```

This again points in the direction that my local development environment is broken, rather than a problem with NevolutionX. Will investigate that later

**Comment by dracc** [comment]
Please run
```
cd build
rm -rf *
cmake ..
make
```
cmake leaves a cache behind which might need to be cleaned upon system changes (newly available packages and the like).

**Comment by Teufelchen1** [comment]
I did that now. It now build inside /NevolutionX/build but the error is still the same (`fatal error: 'threads.h' file not found`). 🤔

**Comment by Teufelchen1** [comment]
Instead of fixing my environment I figured it may be faster to just boot up a virtual computer, setting up new environment in that virtual computer and then build the software in there. 

So my Dockerfile looks like this:
```Dockerfile
FROM python:3.6-slim-buster

RUN apt-get update
RUN apt-get install -y cmake
RUN apt-get install -y clang
RUN apt-get install -y git
RUN apt-get install -y libsdl2-ttf-2.0-0
RUN apt-get install -y libsdl2-ttf-dev

WORKDIR /usr/src/
RUN git clone https://github.com/XboxDev/nxdk.git
```
And in order to build it, I run `docker-compose build && docker-compose run`:
```yaml
version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/src/app/startup.sh
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
```

startup.sh is:
```sh
#!/bin/sh
cd /usr/src/app/build
cmake ..
make
```

**Comment by johnjelinek** [comment]
If I run `make` from root, it works. But if I follow these steps, it fails with https://github.com/dracc/NevolutionX/issues/33#issuecomment-586695289

**Comment by Teufelchen1** [comment]
Yes, with just make from root, it works. Reproducible. Closed! Thanks for the support.
