### ISSUE TITLE
FTP: Not logging in doesn't stop you

### ISSUE THREAD

**Issue by dracc** [dracc/NevolutionX#36]
I have not yet dug deep enough to figure out what the proper response to unauthorized access should be. 403?

**Comment by Teufelchen1** [comment]
According to RFC 959 it's: `530 Not logged in.`

**Comment by dracc** [comment]
> According to RFC 959 it's: `530 Not logged in.`

Thank you @Teufelchen1! I'll take a stab at fixing this right away. :D
