### ISSUE TITLE
Unable to build with nxdk

### ISSUE THREAD

**Issue by chase-cobb** [dracc/NevolutionX#63]
Trying to build with nxdk but getting an error because there is no nxdk/format.h found by wipeCache.cpp.
NevolutionX hash -> 48a28c6
nxdk hash ->  73ea77a

![format_h_error](https://user-images.githubusercontent.com/2946737/115631286-877f5400-a2d3-11eb-95c1-b23b57087804.png)

**Comment by Ryzee119** [comment]
Youre using an old nxdk version. Format header was added recently (commit #86797b5)

**Comment by chase-cobb** [comment]
Grabbed latest nxdk and no longer see that issue, however now in all of my applications I'm seeing " error: <root>: underfined symbol: _WinMainCRTStartup. I'll close this issue though as it is clearly not an issue with this application.
