### ISSUE TITLE
Link to HDD image for the 0.1.1 release appears to download 0.1.0

### ISSUE THREAD

**Issue by trotsky40** [dracc/NevolutionX#68]
The download link in GitHub for the HDD image in the 0.1.1 release (https://github.com/dracc/NevolutionX/releases/download/v0.1.1/nevox_hdd.zip) appears to download the 0.1.0 version. When unzipped, the downloaded file has a date of 3/18. Tried clearing browser cache, different browser, etc...

**Comment by dracc** [comment]
Thank you so much for opening this issue.
Please try again as I've uploaded a new file, generated a couple of minutes ago.

**Comment by trotsky40** [comment]
It is fixed. Thanks.
