### ISSUE TITLE
Xbox-Errorcode 13

### ISSUE THREAD

**Issue by QbikEdge** [dracc/NevolutionX#69]
I am getting the Error code 13 when i try to use it as hard disc for [Xemu][Xemu]. 
But if i use it as Iso disc on  [Xemu][Xemu] it works fine. 

I use the latest Xemu build. Currently: 
Version: 0.5.4-1-g9eefab0e4a
Branch:  master
Commit:  9eefab0e4a866ce9e26271a00a1b0f6b63b3244b

<details><summary>Screenshot while using as HDD</summary>

![image](https://user-images.githubusercontent.com/32527357/121788652-2f781600-cbcf-11eb-8b95-6287f6558d86.png)
</details>

<details><summary>Screenshot while using from Iso as disc drive</summary>

![image](https://user-images.githubusercontent.com/32527357/121788687-854cbe00-cbcf-11eb-97a6-1cc381c3b1ba.png)
</details>

[Xemu]: https://github.com/mborgerson/xemu

**Comment by dracc** [comment]
Thanks for your report, I'll try to reproduce and solve this issue ASAP.

**Comment by dracc** [comment]
Should be fixed with v0.1.2, closing.
