### ISSUE TITLE
Is there a option to mount G: Drive 

### ISSUE THREAD

**Issue by QbikEdge** [dracc/NevolutionX#70]
I am seeing this console output

<details><summary>Screenshot of the console output</summary>

![image](https://user-images.githubusercontent.com/32527357/121791557-50e6fb00-cbeb-11eb-9c49-8ed1e947ab4e.png)
</details>  

So i wondered if it is possible to mount my game directory from windows to the G: Drive in [Xemu] with NevolutionX.    

If it is possible how would i do that? If not could it be a considered as a request? 😃 

[Xemu]: https://github.com/mborgerson/xemu

**Comment by dracc** [comment]
> So i wondered if it is possible to mount my game directory from windows to the G: Drive

That would be a feature of your Xbox, unrelated to NevolutionX.
G: drive in the information line refers to the (optional) extra partition seen in higher capacity hard drives used in order to alleviate some of the shortcomings of LBA48.
