### ISSUE TITLE
NevolutionX  folder structure 

### ISSUE THREAD

**Issue by QbikEdge** [dracc/NevolutionX#72]
# What is the topic?
For the better organizing and a better appearance  we should make a Folder structure.  
Currently its like all the Files are first level of the drive.  

# Why we should do this?
As the project grows it could have more files for configs, skins or other stuff so the C: drive will get cluttered and messy.
We need to address this now to be able avoid that kein of problems later on.

# What i am meaning with Level is:

- `1. Level`
- `1. Level`
  - `2. Level`
    - `3. Level`
  - `2. Level`
- `1. Level`

# My suggestion for the structure:
<details><summary>Details</summary>

- `NevolutionX` [Folder Containing all the files that don't need to be in 1. Level]
  - `Skins` [Folder for different Themes]
    - `Default`
      - `480.png`  
      - `720.png`  
      - `vegur.ttf`  
  - `Config` [Folder for Configurations files if needed]  
  - `default` [I am not sure if this need to be in the 1. Level]  
- `xboxdash`  

</details>

#  Closing words
This is just a way i am suggesting it, but mainly we should just have 1 or 2 files in the 1. level and all the other stuff should be in the folder `NevolutionX`. How the structure in the `NevolutionX` file should be can be discussed.

I hope my point is clear.

**Comment by dracc** [comment]
While the core idea is good, I don't agree with a "NevolutionX" folder as there won't be more than 5-10 files in total on top level anyways.

Theme folder makes sense, once theme support is in place. Planned feature for when the XGU based renderer is completed.

**Comment by QbikEdge** [comment]
I see what you mean. But obviously there would be also other benefits did not write. I want to use NevolutionX not only on Xemu but also on a Real Xbox where are much more Dashboard for various of reasons (Emulation, Homebrew, etc.) and there for it would be much cleaner `C:` Partition.

**Comment by dracc** [comment]
> I see what you mean. But obviously there would be also other benefits did not write. I want to use NevolutionX not only on Xemu but also on a Real Xbox where are much more Dashboard for various of reasons (Emulation, Homebrew, etc.) and there for it would be much cleaner `C:` Partition.

Typical non-issue IMO. Just place your alternative dashboards in folders in E: or F: under `Apps` or even a `Dashboards` folder. C: is cramped as-is, even with just one or two dashboards.

**Comment by QbikEdge** [comment]
> > I see what you mean. But obviously there would be also other benefits did not write. I want to use NevolutionX not only on Xemu but also on a Real Xbox where are much more Dashboard for various of reasons (Emulation, Homebrew, etc.) and there for it would be much cleaner `C:` Partition.
> 
> Typical non-issue IMO. Just place your alternative dashboards in folders in E: or F: under `Apps` or even a `Dashboards` folder. C: is cramped as-is, even with just one or two dashboards.

Its looks like we have different opinions on that. Than I'm closing this if its ok for you!?!

**Comment by MasonT8198** [comment]
I believe it should be fine to close
