### ISSUE TITLE
Graphical corruption when executing the `reboot` menu item

### ISSUE THREAD

**Issue by abaire** [dracc/NevolutionX#79]
Executing the `reboot` item causes the screen to be corrupted until the return to dashboard occurs (looks likely to be uninitialized data).

I assume this is because of the use of `exit()` rather than explicitly launching w/ no executable path. If XboxDev/nxdk/pull/501 gets merged, this can probably be solved by changing the exit to `XLaunchXBE(nullptr)`. 

Calling `XReboot()` also fixes the graphical corruption but that's a full reboot instead of a quick one, which probably isn't desirable for users of bios loaders like Phoenix.

**Comment by abaire** [comment]
Looks like I'm wrong about using an explicit `HalQuickRebootRoutine`; I still see the same corruption after patching 501 and calling `XLaunchXBE` on my v1.0 XBOX.

**Comment by abaire** [comment]
Digging around a bit, I think the issue is the lack of a `PersistDisplay` equivalent to store the framebuffer.
It looks like XVideoInit is already persisting the framebuffer though, so it's not immediately clear to me why the screen doesn't simply freeze.

**Comment by GXTX** [comment]
I'm pretty sure this is an issue with nxdk.

**Comment by abaire** [comment]
Looks like you're right, I can reproduce in a smaller test program. Filed XboxDev/nxdk/issues/507 to track over there.
