### ISSUE TITLE
`MenuXbe` child ordering is case sensitive - should it be?

### ISSUE THREAD

**Issue by abaire** [dracc/NevolutionX#87]
General usability question, right now the ordering of children found via a `MenuXbe` scan are sorted in a case sensitive way.

For example, given XBEs with titles "Esomething" and "aSomething", the resultant menu will be:
- Esomething
- aSomething

Rather than what users might expect:
- aSomething
- ESomething

Is this behavior desired? Given that the sort is only done once it's probably not a performance hit to do something less efficient (like a case insensitive comparison).

**Comment by dracc** [comment]
I've simply not given it enough thought.
Case sensitivity is not by design, rather by coincidence - would love to have it fixed!

**Comment by abaire** [comment]
Fixed by #88
