### ISSUE TITLE
No Video Output

### ISSUE THREAD

**Issue by GXTX** [dracc/NevolutionX#9]
Xbox: 1.2
Cable type: 0x04 (High Definition AV Pack (Component)) | "Pound" cable attached to ASUS monitor
Video standard: 0x01 (NTSC-M)
60 Hz
Enabled HDTV modes {
  HDTV 720p
  HDTV 480p
}
Flags {
  Widescreen
}
MCPX: X3, Revision 0xD4
Video encoder: Conexant
Motherboard: v1.1 or v1.2 or v1.3
SMC: Version 'P11' (503131)
Path: F:\\Apps\\nevolutionx.xbe
BIOS: tsoped ind5004
Launched From: xbmc

_When I get time I'll update this with the exact commit where it stopped working_

**Comment by chrisderwahre** [comment]
This for some reason seems to be a problem with @GXTX 's build, he tried my build that worked fine.

**Comment by GXTX** [comment]
Fresh clones of both nxdk & nevox I still run into the same problem.

**Comment by dracc** [comment]
@GXTX With the merge of xboxdev/nxdk#147, do you get better results?
